[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
crow = "Crow6rDB5ZhGGqV2uXAG6Ta7aLvyw22vRNAcxd7mu2sv"

[programs.mainnet]
crow = "Crow6rDB5ZhGGqV2uXAG6Ta7aLvyw22vRNAcxd7mu2sv"

[test.validator]
url = "https://api.devnet.solana.com"

[[test.validator.clone]]
# Token Metadata program
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
[[test.validator.clone]]
# Token Auth Rules program
address = "auth9SigNpDKz4sJJ1DfCTuZrZNSAgh9sFD3rboVmgg"
[[test.validator.clone]]
# Metaplex ruleSet
address = "eBJLFYPxJmMGKuFwpDWkzxZeUrad92kZRC5BJLpzyT9"

[registry]
url = "https://api.apr.dev"

[test]
upgradeable = true

[provider]
cluster = "Localnet"
wallet = "/Users/joefitter/.config/solana/id.json"
# cluster = "Mainnet"
# wallet = "/Users/joefitter/.config/solana/launchpad/dandies/holding.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
